# Generated by Django 4.2.2 on 2023-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.TextField(unique=True),
        ),
    ]
