# Generated by Django 4.2.2 on 2023-07-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
